name: Package Commits and PRs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: TurboRepo Build
        run: bun turbo build -F "{$(bun --silent get-package-list)}"

      - run: bunx pkg-pr-new publish 'packages/*'
