name: Package Commits and PRs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build @hypermd/core
        run: bun --filter="@hypermd/core" run build

      - name: Build @hypermd/render-html
        run: bun --filter="@hypermd/render-html" run build

      - run: bunx pkg-pr-new publish 'packages/*'
