name: Package Commits and PRs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: bun install --frozen-lockfile

      - name: Install package dependencies
        run: bun install --frozen-lockfile --filter="@hypermd/*"

      - name: Build
        run: bun --filter="@hypermd/*" run build

      - run: bunx pkg-pr-new publish 'packages/*'
